apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_URL: jdbc:postgresql://postgres:5432/mydatabase
  MINIO_ENDPOINT: http://minio:9000
  MINIO_DEFAULT_BUCKET: test-bucket
  K8S_NAMESPACE: demo
  TRANSFORM_IMAGE_DOCKER_IMAGE: ghcr.io/yimwaikei/demo-kubernetes-scripts:b39ae977dab472c134dda2726b06be2c4f71f571
