apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  labels:
    app: demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      serviceAccountName: job-runner
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: demo-backend
          image: ghcr.io/yimwaikei/demo-kubernetes-backend:957f78e076c2566e7b15fd11e5e4cd4c3b870ac5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: POSTGRES_PASSWORD
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MINIO_ENDPOINT
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_DEFAULT_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MINIO_DEFAULT_BUCKET
            - name: K8S_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: K8S_NAMESPACE
            - name: TRANSFORM_IMAGE_DOCKER_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: TRANSFORM_IMAGE_DOCKER_IMAGE
