apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  labels:
    app: demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: demo-frontend
          image: ghcr.io/yimwaikei/demo-kubernetes-frontend:demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_BACKEND_URL
