apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets/database-secret.yaml
  - secrets/s3-secret.yaml
  - ingress.yaml
  - rbac/serviceaccounts.yaml
  - rbac/roles.yaml
  - rbac/rolebindings.yaml
  - database/
  - backend/
  - frontend/
  - s3/
