apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
spec:
  selector:
    app: {{ .Release.Name }}-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30092
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30093
  type: NodePort
